# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QQScrollView' do

inhibit_all_warnings!
    
pod 'AFNetworking'
pod 'MJExtension'
pod 'Mantle'
pod 'SDWebImage'
pod 'Masonry'
pod 'SDCycleScrollView'                     # 轮播图
pod 'MJRefresh'                             # 刷新控件
pod 'MBProgressHUD'

end
